<Project>
  <PropertyGroup>
    <Product>AutoWeldSystem</Product>
    <Company>AutoWeldSystem</Company>
    <Version>1.11.1</Version>
    <AssemblyVersion>1.11.1.0</AssemblyVersion>
    <FileVersion>1.11.1.0</FileVersion>
    <InformationalVersion>1.11.1</InformationalVersion>
  </PropertyGroup>
</Project>
