<Project>
  <PropertyGroup>
    <Product>AutoWeldSystem</Product>
    <Company>AutoWeldSystem</Company>
    <Version>1.8.3</Version>
    <AssemblyVersion>1.8.3.0</AssemblyVersion>
    <FileVersion>1.8.3.0</FileVersion>
    <InformationalVersion>1.8.3</InformationalVersion>
  </PropertyGroup>
</Project>
