<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoWeldSystem.Core\AutoWeldSystem.Core.csproj" />
    <ProjectReference Include="..\AutoWeldSystem.Data\AutoWeldSystem.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Plc\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="HslCommunication">
      <HintPath>..\AutoWeldSystem.Libs\HslCommunication.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
