using AutoWeldSystem.Core.Constants;
using SqlSugar;

namespace AutoWeldSystem.Core.Models;

/// <summary>
/// Weld point collection record.
/// One row represents one weld start/end cycle for a specific ProductNo and TouchNo.
/// </summary>
[SugarTable("Biz_WeldPointRecord", TableDescription = "焊点采集记录表")]
public class BizWeldPointRecord
{
    [SugarColumn(IsPrimaryKey = true, IsIdentity = true)]
    public int Id { get; set; }

    /// <summary>
    /// Local weld task id.
    /// </summary>
    [SugarColumn(ColumnDescription = "焊接任务ID")]
    public int TaskId { get; set; }

    /// <summary>
    /// MES start task id returned by ExpStart.
    /// </summary>
    [SugarColumn(Length = 50, IsNullable = true, ColumnDescription = "开工任务ID")]
    public string? ExpStartId { get; set; }

    [SugarColumn(Length = 50, ColumnDescription = "设备编号")]
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// Work order number / flow card number.
    /// </summary>
    [SugarColumn(Length = 50, ColumnDescription = "工单号")]
    public string SN { get; set; } = string.Empty;

    [SugarColumn(Length = 50, ColumnDescription = "工序号")]
    public string ProcessNo { get; set; } = string.Empty;

    /// <summary>
    /// Unique product number generated by the PC for the current work order.
    /// </summary>
    [SugarColumn(Length = 50, ColumnDescription = "产品编号")]
    public string ProductNo { get; set; } = string.Empty;

    /// <summary>
    /// Weld point number under one ProductNo.
    /// </summary>
    [SugarColumn(Length = 50, ColumnDescription = "焊点编号")]
    public string TouchNo { get; set; } = string.Empty;

    [SugarColumn(ColumnDescription = "工位号")]
    public int StationNo { get; set; }

    [SugarColumn(ColumnDescription = "采集序号")]
    public int SequenceNo { get; set; }

    [SugarColumn(Length = 50, IsNullable = true, ColumnDescription = "峰值电流")]
    public string? MaxElectric { get; set; }

    [SugarColumn(Length = 50, IsNullable = true, ColumnDescription = "峰值电压")]
    public string? MaxVoltage { get; set; }

    [SugarColumn(Length = 50, IsNullable = true, ColumnDescription = "有效功率")]
    public string? ValidPower { get; set; }

    [SugarColumn(Length = 100, IsNullable = true, ColumnDescription = "位移")]
    public string? Displacement { get; set; }

    [SugarColumn(Length = 100, IsNullable = true, ColumnDescription = "焊接时间")]
    public string? WeldTs { get; set; }

    [SugarColumn(Length = 20, ColumnDescription = "数据类型")]
    public string Type { get; set; } = "EM";

    /// <summary>
    /// Raw PLC result value. Confirmed rule: 3 means OK; all other values mean NG.
    /// </summary>
    [SugarColumn(Length = 20, IsNullable = true, ColumnDescription = "测试结果原始值")]
    public string? TestResultRaw { get; set; }

    [SugarColumn(Length = 20, ColumnDescription = "测试结果")]
    public string TestResult { get; set; } = ProductionConstants.TestResults.Unknown;

    [SugarColumn(Length = 50, IsNullable = true, ColumnDescription = "操作员工号")]
    public string? OperatorNo { get; set; }

    [SugarColumn(ColumnDescription = "采集时间")]
    public DateTime RecordTime { get; set; } = DateTime.Now;

    /// <summary>
    /// Whether all weld points for this ProductNo have been collected.
    /// </summary>
    [SugarColumn(ColumnDescription = "产品是否采集完成")]
    public bool ProductCompleted { get; set; }

    [SugarColumn(Length = 20, ColumnDescription = "上传状态")]
    public string UploadStatus { get; set; } = ProductionConstants.UploadStatuses.Pending;

    [SugarColumn(IsNullable = true, ColumnDescription = "上传时间")]
    public DateTime? UploadTime { get; set; }

    [SugarColumn(ColumnDataType = "text", IsNullable = true, ColumnDescription = "上传消息")]
    public string? UploadMessage { get; set; }

    [SugarColumn(ColumnDescription = "重试次数")]
    public int RetryCount { get; set; }

    /// <summary>
    /// Raw collection values serialized as JSON for later troubleshooting and dynamic report columns.
    /// </summary>
    [SugarColumn(ColumnDataType = "text", IsNullable = true, ColumnDescription = "原始采集JSON")]
    public string? RawDataJson { get; set; }
}
