using AutoWeldSystem.Core.Constants;

namespace AutoWeldSystem.Core.Security;

public static class PermissionTextKeyMapper
{
    public static string GetTextKey(string permissionCode)
    {
        return permissionCode switch
        {
            PermissionCodes.Pages.Monitor => TextKeys.Permission.PageMonitor,
            PermissionCodes.Pages.DataManage => TextKeys.Permission.PageDataManage,
            PermissionCodes.Pages.UserManage => TextKeys.Permission.PageUserManage,
            PermissionCodes.Pages.ProgramManage => TextKeys.Permission.PageProgramManage,
            PermissionCodes.Pages.LogManage => TextKeys.Permission.PageLogManage,
            PermissionCodes.Pages.StateManage => TextKeys.Permission.PageStateManage,
            PermissionCodes.Pages.SystemSetting => TextKeys.Permission.PageSystemSetting,
            PermissionCodes.Pages.AddressManage => TextKeys.Permission.PageAddressManage,
            PermissionCodes.Buttons.Monitor.OnlineReport => TextKeys.Permission.ButtonMonitorOnlineReport,
            PermissionCodes.Buttons.Monitor.LocalWorkOrder => TextKeys.Permission.ButtonMonitorLocalWorkOrder,
            PermissionCodes.Buttons.Auth.SwitchUser => TextKeys.Permission.ButtonAuthSwitchUser,
            PermissionCodes.Buttons.Auth.Logout => TextKeys.Permission.ButtonAuthLogout,
            PermissionCodes.Buttons.Auth.AddressPreview => TextKeys.Permission.ButtonAuthAddressPreview,
            PermissionCodes.Buttons.Data.Query => TextKeys.Permission.ButtonDataQuery,
            PermissionCodes.Buttons.Data.Reset => TextKeys.Permission.ButtonDataReset,
            PermissionCodes.Buttons.Data.OpenReport => TextKeys.Permission.ButtonDataOpenReport,
            PermissionCodes.Buttons.Data.OpenReportFolder => TextKeys.Permission.ButtonDataOpenReportFolder,
            PermissionCodes.Buttons.User.Add => TextKeys.Permission.ButtonUserAdd,
            PermissionCodes.Buttons.User.Edit => TextKeys.Permission.ButtonUserEdit,
            PermissionCodes.Buttons.User.Delete => TextKeys.Permission.ButtonUserDelete,
            PermissionCodes.Buttons.User.AssignRole => TextKeys.Permission.ButtonUserAssignRole,
            PermissionCodes.Buttons.User.ResetPassword => TextKeys.Permission.ButtonUserResetPassword,
            PermissionCodes.Buttons.Role.Add => TextKeys.Permission.ButtonRoleAdd,
            PermissionCodes.Buttons.Role.Edit => TextKeys.Permission.ButtonRoleEdit,
            PermissionCodes.Buttons.Role.Delete => TextKeys.Permission.ButtonRoleDelete,
            PermissionCodes.Buttons.Role.Refresh => TextKeys.Permission.ButtonRoleRefresh,
            PermissionCodes.Buttons.Role.AssignPermissions => TextKeys.Permission.ButtonRoleAssignPermissions,
            PermissionCodes.Buttons.Program.Add => TextKeys.Permission.ButtonProgramAdd,
            PermissionCodes.Buttons.Program.Edit => TextKeys.Permission.ButtonProgramEdit,
            PermissionCodes.Buttons.Program.Delete => TextKeys.Permission.ButtonProgramDelete,
            PermissionCodes.Buttons.Program.Sync => TextKeys.Permission.ButtonProgramSync,
            PermissionCodes.Buttons.Program.PullMes => TextKeys.Permission.ButtonProgramPullMes,
            PermissionCodes.Buttons.Program.Refresh => TextKeys.Permission.ButtonProgramRefresh,
            PermissionCodes.Buttons.Program.BuildName => TextKeys.Permission.ButtonProgramBuildName,
            PermissionCodes.Buttons.Log.Refresh => TextKeys.Permission.ButtonLogRefresh,
            PermissionCodes.Buttons.Log.OpenFolder => TextKeys.Permission.ButtonLogOpenFolder,
            PermissionCodes.Buttons.Log.OpenSource => TextKeys.Permission.ButtonLogOpenSource,
            PermissionCodes.Buttons.Log.CopyDetails => TextKeys.Permission.ButtonLogCopyDetails,
            PermissionCodes.Buttons.State.RetrySelected => TextKeys.Permission.ButtonStateRetrySelected,
            PermissionCodes.Buttons.State.RetryAll => TextKeys.Permission.ButtonStateRetryAll,
            PermissionCodes.Buttons.State.Refresh => TextKeys.Permission.ButtonStateRefresh,
            PermissionCodes.Buttons.State.UploadAll => TextKeys.Permission.ButtonStateUploadAll,
            PermissionCodes.Buttons.State.Delete => TextKeys.Permission.ButtonStateDelete,
            PermissionCodes.Tabs.State.WorkOrderInfo => TextKeys.Permission.TabStateWorkOrderInfo,
            PermissionCodes.Tabs.State.StartReport => TextKeys.Permission.TabStateStartReport,
            PermissionCodes.Tabs.State.FinishReport => TextKeys.Permission.TabStateFinishReport,
            PermissionCodes.Tabs.State.ProcessParameter => TextKeys.Permission.TabStateProcessParameter,
            PermissionCodes.Tabs.State.ReportFile => TextKeys.Permission.TabStateReportFile,
            PermissionCodes.Tabs.State.WorkOrderStatus => TextKeys.Permission.TabStateWorkOrderStatus,
            PermissionCodes.Tabs.State.DeviceStatus => TextKeys.Permission.TabStateDeviceStatus,
            PermissionCodes.Tabs.State.ProgramFile => TextKeys.Permission.TabStateProgramFile,
            PermissionCodes.Tabs.Log.MesInteraction => TextKeys.Permission.TabLogMesInteraction,
            PermissionCodes.Tabs.Log.ProductionFlow => TextKeys.Permission.TabLogProductionFlow,
            PermissionCodes.Tabs.Log.ProgramException => TextKeys.Permission.TabLogProgramException,
            PermissionCodes.Tabs.Log.Device => TextKeys.Permission.TabLogDevice,
            PermissionCodes.Tabs.Log.DeviceStatus => TextKeys.Permission.TabLogDeviceStatus,
            PermissionCodes.Tabs.Log.Server => TextKeys.Permission.TabLogServer,
            PermissionCodes.Tabs.Address.BusinessSignal => TextKeys.Permission.TabAddressBusinessSignal,
            PermissionCodes.Tabs.Address.RecipeName => TextKeys.Permission.TabAddressRecipeName,
            PermissionCodes.Tabs.Address.Alarm => TextKeys.Permission.TabAddressAlarm,
            PermissionCodes.Tabs.Address.ProductProcess => TextKeys.Permission.TabAddressProductProcess,
            PermissionCodes.Tabs.Address.TestPlan => TextKeys.Permission.TabAddressTestPlan,
            PermissionCodes.Tabs.Address.PlanDetail => TextKeys.Permission.TabAddressPlanDetail,
            PermissionCodes.Tabs.Address.TestItemDictionary => TextKeys.Permission.TabAddressTestItemDictionary,
            PermissionCodes.Buttons.SystemSetting.Save => TextKeys.Permission.ButtonSystemSave,
            PermissionCodes.Buttons.SystemSetting.ConnectPlc => TextKeys.Permission.ButtonSystemConnectPlc,
            PermissionCodes.Buttons.SystemSetting.SyncDevice => TextKeys.Permission.ButtonSystemSyncDevice,
            PermissionCodes.Buttons.SystemSetting.TestMes => TextKeys.Permission.ButtonSystemTestMes,
            PermissionCodes.Buttons.SystemSetting.ChangePath => TextKeys.Permission.ButtonSystemChangePath,
            PermissionCodes.Buttons.SystemSetting.OpenPath => TextKeys.Permission.ButtonSystemOpenPath,
            PermissionCodes.Buttons.Address.Save => TextKeys.Permission.ButtonAddressSave,
            PermissionCodes.Buttons.Address.Refresh => TextKeys.Permission.ButtonAddressRefresh,
            PermissionCodes.Buttons.Address.Test => TextKeys.Permission.ButtonAddressTest,
            PermissionCodes.Buttons.Address.AddAlarm => TextKeys.Permission.ButtonAddressAddAlarm,
            PermissionCodes.Buttons.Address.DeleteAlarm => TextKeys.Permission.ButtonAddressDeleteAlarm,
            PermissionCodes.Buttons.Address.PasteAlarm => TextKeys.Permission.ButtonAddressPasteAlarm,
            PermissionCodes.Buttons.Address.AddProductProcess => TextKeys.Permission.ButtonAddressAddProductProcess,
            PermissionCodes.Buttons.Address.DeleteProductProcess => TextKeys.Permission.ButtonAddressDeleteProductProcess,
            PermissionCodes.Buttons.Address.PreviewProductProcessAddress => TextKeys.Permission.ButtonAddressPreviewProductProcessAddress,
            PermissionCodes.Buttons.Address.AddScheme => TextKeys.Permission.ButtonAddressAddScheme,
            PermissionCodes.Buttons.Address.DeleteScheme => TextKeys.Permission.ButtonAddressDeleteScheme,
            PermissionCodes.Buttons.Address.AddTestItem => TextKeys.Permission.ButtonAddressAddTestItem,
            PermissionCodes.Buttons.Address.DeleteTestItem => TextKeys.Permission.ButtonAddressDeleteTestItem,
            _ => string.Empty
        };
    }
}
